# Generated by Django 3.1.5 on 2021-02-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='audated',
            new_name='updated',
        ),
    ]
